### PR TITLE
Add typescript definitions

### PR DESCRIPTION
**Pull request by syabro**
#11

### CODE REVIEW

**Comment by mariocasciaro** [comment]
Thanks @syabro and sorry for the wait

**Comment by syabro** [comment]
@mariocasciaro thanks :) I know it's hard to find a minute sometimes
v.0.5.1 maybe?

**Comment by mariocasciaro** [comment]
The new version should be out already 👍

**Comment by ulrichb** [comment]
Hi. Thanks for the .d.ts.

Should we copy/move this to https://github.com/DefinitelyTyped/DefinitelyTyped/? (To be able to reference it by using `@types/object-path-immutable`)?

**Comment by syabro** [comment]
@ulrichb nope. `@types` is being used when repo owner doesn't want to keep `d.ts` file in his repo.

**Comment by ulrichb** [comment]
@syabro Yes, didn't know that there is this new  mechanism using a package.json attribute. Therefore I proposed #30.

**Pull request merged**
